const express = require("express");
const {addtocart,Buyerlogin,BuyersignUp,sendMail,cartdata, getemail, updatebuyer} = require("../controllers/buyer-controller");
const signupSchema = require("../middleware/auth-middleware");
const validate = require("../validators/auth-validator");
const router = express.Router();
router.route("/signup").post(validate(signupSchema),BuyersignUp);
router.route("/login").post(Buyerlogin);
router.route("/addtocart").post(addtocart);
router.route("/getcart/:id").get(cartdata);
router.route("/forgetp").post(getemail);
router.route("/cpass/:id").post(updatebuyer);
// router.route("/delete/:id").delete(DelCart);
router.route("/sendmail/:email").post(sendMail);
module.exports = router; 